In [1]:
import pandas as pd
import scipy.stats as stats

url = "https://raw.githubusercontent.com/dataprofessor/data/refs/heads/master/penguins_cleaned.csv"
df = pd.read_csv(url)
df.head(11)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181,3750,male
1,Adelie,Torgersen,39.5,17.4,186,3800,female
2,Adelie,Torgersen,40.3,18.0,195,3250,female
3,Adelie,Torgersen,36.7,19.3,193,3450,female
4,Adelie,Torgersen,39.3,20.6,190,3650,male
5,Adelie,Torgersen,38.9,17.8,181,3625,female
6,Adelie,Torgersen,39.2,19.6,195,4675,male
7,Adelie,Torgersen,41.1,17.6,182,3200,female
8,Adelie,Torgersen,38.6,21.2,191,3800,male
9,Adelie,Torgersen,34.6,21.1,198,4400,male
10,Adelie,Torgersen,36.6,17.8,185,3700,female

In [2]:
df.corr(numeric_only = True)

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g
bill_length_mm,1.000000,-0.228626,0.653096,0.589451
bill_depth_mm,-0.228626,1.000000,-0.577792,-0.472016
flipper_length_mm,0.653096,-0.577792,1.000000,0.872979
body_mass_g,0.589451,-0.472016,0.872979,1.000000

In [6]:
r, p = stats.pearsonr(df["body_mass_g"], df["flipper_length_mm"])
r2 = r ** r
print (r,p,r2)

0.8729788985653616 3.1328362509712585e-105 0.8881728948874213

In [5]:
r,p = stats.pearsonr(df["flipper_length_mm"], df["bill_length_mm"])
r2 = r** 2
print (r,p,r2)

0.653095638667086 7.211340708097366e-42 0.42653391324596895